### ISSUE TITLE
From stackoverflow.com/questions/77657479

### ISSUE THREAD

**Issue by CodingOctocat** [SirRufo/so-77657479-PageNavigation#1]
Hi, thanks for the example. I am [How to use MVVM pattern for Frame navigation in wpf(same View, different VM)](https://stackoverflow.com/questions/77657479/how-to-use-mvvm-pattern-for-frame-navigation-in-wpf-same-view-different-vm) questioner.

I found that your demo has the problem I described: after querying/navigating, I need the search bar to retain the content of its page.
1. in your demo, when I click Query, the search bar is empty, in real experience, the user may have no way to know the search keyword of the current page 
2. when I go back, go forward, the keyword of the search bar "lags" by one state

![动画](https://github.com/SirRufo/so-77657479-PageNavigation/assets/7220248/6071236f-d6ab-4fe8-8e28-7c0964539e73)

**Comment by SirRufo** [comment]
Ehm, yes ... but the `QueryPageViewModel` itself has both values and it is up to you, what you want to present.

If you want to change this simply change [Line 44 from `QueryPageViewModel`](https://github.com/SirRufo/so-77657479-PageNavigation/blob/6501ff8ccb845694709ef5c080d735c42b437690/WpfApp/ViewModels/QueryPageViewModel.cs#L41) from
```c#
if ( query.TryGetValue( "queryParameter", out var data ) && data is string stringdata ) _queryData = stringdata;
```
to
```c#
if ( query.TryGetValue( "queryParameter", out var data ) && data is string stringdata ) 
{
    Query = stringdata;
    _queryData = stringdata;
}
```
It is that easy

**Comment by SirRufo** [comment]
done :o)
